bg: TurkuNLP/wikibert-base-bg-cased
cs: TurkuNLP/wikibert-base-cs-cased
da: Maltehb/danish-bert-botxo
de: bert-base-german-cased
el: nlpaueb/bert-base-greek-uncased-v1
en: nlpaueb/legal-bert-base-uncased
es: dccuchile/bert-base-spanish-wwm-cased
et: tartuNLP/EstBERT
fi: TurkuNLP/bert-base-finnish-cased-v1
fr: camembert-base
hu: SZTAKI-HLT/hubert-base-cc
it: dbmdz/bert-base-italian-cased
lt: TurkuNLP/wikibert-base-lt-cased
lv: TurkuNLP/wikibert-base-lv-cased
mt: bert-base-multilingual-cased
nl: wietsedv/bert-base-dutch-cased
pl: dkleczek/bert-base-polish-cased-v1
pt: neuralmind/bert-base-portuguese-cased
ro: dumitrescustefan/bert-base-romanian-cased-v1
sk: TurkuNLP/wikibert-base-sk-cased
sl: TurkuNLP/wikibert-base-sl-cased
sv: KB/bert-base-swedish-cased